<a href="https://colab.research.google.com/github/sofilailatul/DataMining/blob/main/percobaan2_modul12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load dataset Iris
iris = load_iris()
X = iris.data
y = iris.target

# Bagi data menjadi data pelatihan dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standarisasi fitur
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Inisialisasi dan pelatihan model MLPClassifier
mlp = MLPClassifier (hidden_layer_sizes=(2,), max_iter=5000, alpha=0.01, solver='adam', random_state=42)
mlp.fit(X_train, y_train)

# Prediksi pada data uji
y_pred = mlp.predict(X_test)

In [11]:
#Evaluasi model
accuracy = accuracy_score (y_test, y_pred)
print (f'Akurasi: {accuracy* 100}%')
print(classification_report (y_test, y_pred, target_names=iris.target_names))

#Menampilkan arsitektur jaringan syaraf
print("\nArsitektur Neural Network: ")
print (f"Input Layer: {X_train.shape[1]} neurons")
for i, size in enumerate (mlp.hidden_layer_sizes):
  print(f"Hidden Layer {i + 1}: {size} neurons")
  print (f"Output Layer: {mlp.n_outputs_} neurons")
  print (f"Fungsi Aktivasi: {mlp.activation}")

# Jika ingin melihat bobot dan bias hasil pelatihan
print("\nBobot dan Bias: ")
print("Bobot antara input dan hidden layer: ")
print (mlp.coefs_[0])
print("Bobot antara hidden dan output layer: ")
print(mlp.coefs_[1])
print("Biase dari hidden layer: ")
print (mlp.intercepts_[0])
print("Bias dari output layer:")
print (mlp.intercepts_[1])

Akurasi: 96.66666666666667%
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.89      0.94         9
   virginica       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30


Arsitektur Neural Network: 
Input Layer: 4 neurons
Hidden Layer 1: 2 neurons
Output Layer: 3 neurons
Fungsi Aktivasi: relu

Bobot dan Bias: 
Bobot antara input dan hidden layer: 
[[ 0.29043092  0.37942107]
 [-0.11143083 -0.92803836]
 [-0.12502741  1.30316477]
 [-0.319365    3.00535738]]
Bobot antara hidden dan output layer: 
[[-0.68226519  0.66971868  0.33982245]
 [-2.13634104 -0.01405818  0.64075203]]
Biase dari hidden layer: 
[-0.36447033  1.46672126]
Bias dari output layer:
[ 1.66226276 -0.12257475 -2.92008277]
